version: '3.4'

services:
  server:
    image: nnhathung97/eventyay-video:development-server
    ports:
      - "8375:8375"
    volumes:
      - ./server:/app:ro
      - appdata:/data
    environment:
      - DB_URL=postgresql://venueless:venueless@db:5432/venueless
      - REDIS_URL=redis://redis:6379/0
      - REDIS_URL_CACHE=redis://redis1:6379/1
    depends_on:
      - db
      - redis
      - redis1
    entrypoint: ["bash", "/app/docker-dev-entrypoint.sh"]

  celery:
    image: nnhathung97/eventyay-video:development-server
    volumes:
      - ./server:/app:ro
      - appdata:/data
    environment:
      - DB_URL=postgresql://venueless:venueless@db:5432/venueless
      - REDIS_URL=redis://redis:6379/0
      - REDIS_URL_CACHE=redis://redis1:6379/1
    depends_on:
      - db
      - redis
      - redis1
    entrypoint: ["bash", "/app/docker-dev-entrypoint-celery.sh"]

  webapp:
    image: nnhathung97/eventyay-video:development-webapp
    ports:
      - "8880:8880"
    volumes:
      - ./webapp:/app:ro
    command: npm start -- --host 0.0.0.0

  redis:
    image: redis:latest

  redis1:
    image: redis:latest

  db:
    image: postgres:15
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=md5
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_USER=venueless
      - POSTGRES_PASSWORD=venueless

volumes:
  postgres_data:
  appdata:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.0.0/16
