FROM python:3.11-bookworm



# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt /requirements.txt
RUN apt update && apt install -y poppler-utils && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip3 install -U pip wheel setuptools && pip3 install -Ur requirements.txt
ENV VENUELESS_COMMIT_SHA=devcontainer
# Set the working directory in the container
WORKDIR /app
# Make port 8375 available to the world outside this container
EXPOSE 8375
