name: Main workflow

on:
  push:
    branches:
      - testing1
  pull_request:
    branches:
      - testing1
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: nnhathung97
        password: 1235123@Tm@

    - name: Build and push server Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./server
        file: ./server/Dockerfile-dev
        push: true
        tags: nnhathung97/eventyay-video:testing-server

    - name: Build and push webapp Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: nnhathung97/eventyay-video:testing-webapp

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: push_to_registry

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        eval "$(ssh-agent -s)"
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Copy docker-compose file
      run: |
        scp docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/eventyay/eventyay-videos

    - name: Deploy using docker-compose
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd /home/eventyay/eventyay-videos && sudo docker-compose pull && sudo docker-compose up -d"
